apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: hello-world
spec:
  containers:
    - name: client
      image: turbothinh/node-10-hello-world # Docker image that has been pushed to registry
      ports:
        - containerPort: 8080 # Point this to container exposed port
      resources:
        limits:
          memory: 200Mi
        requests:
          memory: 100Mi

  restartPolicy: Always # Always restart on error