apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-worker-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: redis-worker

  template:
    metadata:
      labels:
        app: redis-worker
    spec:
      containers:
        - name: redis-worker
          image: turbothinh/k8s-boiler-redis-worker
          resources:
            limits:
              memory: "256Mi"
              cpu: "2"
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip
            - name: REDIS_PORT
              value: '6379'
          
