apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment

spec:
  replicas: 2 # create 2 pods using the container template

  selector:
    matchLabels:
      app: server

  template: # Template for a pod
    metadata:
      labels:
        app: server

    spec:
      containers:
        - name: server
          image: turbothinh/k8s-boiler-server
          ports:
            - containerPort: 8080 # Port exposed from a container
          resources:
            limits:
              memory: "256Mi"
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip
            - name: REDIS_PORT
              value: '6379'

            - name: PGHOST
              value: postgres-cluster-ip
            - name: PGUSER
              value: postgres
            - name: PGPORT
              value: '5432'
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-pgpassword
                  key: PGPASSWORD
